### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mietek** [mietek/haskell-on-heroku#23]
- [x] Clarify using S3 is optional _only_ for applications which use an existing sandbox, compile successfully within the 15 minute limit, and which don't need to keep their dependencies for later.
- [x] Clarify most apps should be using S3, following #10.
- [x] Clarify `build` will always build all necessary packages, following #10.
- [x] Avoid mentioning `heroku repo:rebuild` in favour of `git commit --amend --no-edit && git push heroku master`, following #11.
- [x] Explain how to deal with the 15-minute build limit, following #11.
- [x] Warn about 4GB RAM required for building e.g. Spock.
- [x] Describe all files stored on S3, and commands which can be used to manage them.
- [x] Describe all external tool dependencies.
- [x] List all used workarounds for Cabal issues.
